language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - ROOT=5.34.32
  - ROOT=6.04
  - ROOT=NONE

# stop duplicate jobs
matrix:
  exclude:
    # - python: 3.4
    #   env: ROOT=5.34.32
    - python: 3.5
      env: ROOT=5.34.32
    - python: 3.5
      env: ROOT=6.04
    - python: 3.6
      env: ROOT=5.34.32
    - python: 3.6
      env: ROOT=6.04

# don't add osx, python not supported
os:
  - linux

install:
  - if [[ ${TRAVIS_OS_NAME} == linux ]]; then wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a # Useful for debugging any issues with conda
  - conda config --add channels http://conda.anaconda.org/NLeSC
  - conda config --set show_channel_urls yes
  - echo $TRAVIS_PYTHON_VERSION
  - MYENV=testenv
  - conda create -q -n ${MYENV} python=${TRAVIS_PYTHON_VERSION}
  - export CONDA_ENV_PATH=$HOME/miniconda/envs/${MYENV}
  - source activate ${MYENV}
  # - if [[ ${ROOT} != "" ]]; then conda install root=${ROOT}; fi
  - conda install root=${ROOT}
  - source deactivate ${MYENV}
  - source activate ${MYENV}

script:
  - which root
  - root -q -b test-root.C
  - python test-root.py
