language: python
matrix:
  include:
    - python: 2.7
      env: PYTHON=2.7 ROOT=5.34.32
    - python: 2.7
      env: PYTHON=2.7 ROOT=6.04

cache:
  - apt

os:
  - linux

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a # Useful for debugging any issues with conda
  - conda config --add channels http://conda.anaconda.org/NLeSC
  - conda config --set show_channel_urls yes
  - conda create -q -n testenv python=${PYTHON} root=${ROOT} root-numpy numpy matplotlib nose sphinx pytables
  - export CONDA_ENV_PATH=$HOME/miniconda/envs/testenv
  - source activate testenv

  # - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  # - sudo apt-get update -q
  # - sudo apt-get install gcc-5 -y
  # - wget https://root.cern.ch/download/root_v6.08.04.Linux-ubuntu16-x86_64-gcc5.4.tar.gz -O /tmp/root.tar.gz
  # - tar -xzf /tmp/root.tar.gz
  # - ls
  # - . root/bin/thisroot.sh

# command to run tests, e.g. python setup.py test
script:
  - which root
  - root -q -b test-root.C
  - python test-root.py
